### ISSUE TITLE
gpg: keyserver receive failed: No data

### ISSUE THREAD

**Issue by ammaratef45** [yegor256/rultor-remote#20]
When I run this command in windows
`D:\Ammar>rultor encrypt -p ammaratef45/Attendance-Admin api-project.json`
I get the following log

>gpg (GnuPG) 2.2.11
libgcrypt 1.8.4
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Home: C:/Users/ammar/AppData/Roaming/gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
gpg: using cipher AES
gpg: writing to './api-project.json.enc'
gpg: data source: http://108.51.167.248:11371
gpg: keyserver receive failed: No data
Traceback (most recent call last):
        8: from C:/Ruby25-x64/bin/rultor:23:in `<main>'
        7: from C:/Ruby25-x64/bin/rultor:23:in `load'
        6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rultor-0.4.4/bin/rultor:39:in `<top (required)>'
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rultor-0.4.4/bin/rultor:48:in `block (3 levels) in <top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rultor-0.4.4/lib/rultor/encrypt.rb:55:in `run': PGP encryption failed (RuntimeError)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by kreinba** [comment]
@ammaratef45 thanks for reporting this, @yegor256 I'd like to take a look and submit a fix. If anyone has objections or is already working on it, please let me know.

**Comment by kreinba** [comment]
@ammaratef45 a fix is now up at https://github.com/yegor256/rultor-remote/pull/24 — it bundles the Rultor public key inside the gem so `gpg --recv-keys` is no longer needed and the encryption works without a reachable keyserver.
