### ISSUE TITLE
Environment variable -x not defined

### ISSUE THREAD

**Issue by pavanputhra** [yegor256/rultor-remote#9]
Hi, am using the following command in windows

$ rultor encrypt -p mahoujas/smsowl-javat secring.gpg

I get following error.

Environment variable -x not defined
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rultor-0.4.1/lib/rultor/encrypt.rb:77:in `run': Failed to PGP encrypt (RuntimeError)
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rultor-0.4.1/bin/rultor:48:in `block (3 levels) in <top (required)="">'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rultor-0.4.1/bin/rultor:39:in `<top (required)="">'
from C:/Ruby22-x64/bin/rultor:23:in `load'
from C:/Ruby22-x64/bin/rultor:23:in `<main>'

**Comment by yegor256** [comment]
@pavanputhra I didn't test it on Windows... let me try and I'll get back to you

**Comment by dmzaytsev** [comment]
@yegor256 I have same issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.2`

**Comment by yegor256** [comment]
@pavanputhra @dmzaytsev I believe, version 0.4.2 doesn't have a bug any more, please try

**Comment by dmzaytsev** [comment]
@yegor256 I confirm the encrypt feature  works on windows 8.1 now
